# Generated by Django 3.0.8 on 2021-04-18 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='descriptions',
        ),
    ]
